name = "kproment2-policy-fund"
compatibility_date = "2024-01-01"

[env.production]
name = "kproment2-policy-fund"

[[d1_databases]]
binding = "kproment2-db"
database_name = "kproment2-db"
database_id = "your-database-id-here"

[build]
command = "echo 'Static site - no build needed'"
cwd = "."
watch_dir = "."

[[pages.functions]]
pattern = "/api/*"
