name = "allinpay-loan-chat"
compatibility_date = "2024-01-01"

[env.production]
name = "allinpay-loan-chat"

[[d1_databases]]
binding = "DB"
database_name = "allinpay-db"
database_id = "b6b8a9a8-d182-498a-9c41-c86b751e8ee3"

[build]
command = "echo 'Static site - no build needed'"
cwd = "."
watch_dir = "."

[[pages.functions]]
pattern = "/api/*"
